set(_CATKIN_CURRENT_PACKAGE "nav_msgs")
set(nav_msgs_VERSION "1.12.7")
set(nav_msgs_MAINTAINER "Tully Foote <tfoote@osrfoundation.org>")
set(nav_msgs_PACKAGE_FORMAT "1")
set(nav_msgs_BUILD_DEPENDS "geometry_msgs" "message_generation" "std_msgs" "actionlib_msgs")
set(nav_msgs_BUILD_EXPORT_DEPENDS "geometry_msgs" "message_runtime" "std_msgs" "actionlib_msgs")
set(nav_msgs_BUILDTOOL_DEPENDS "catkin")
set(nav_msgs_BUILDTOOL_EXPORT_DEPENDS )
set(nav_msgs_EXEC_DEPENDS "geometry_msgs" "message_runtime" "std_msgs" "actionlib_msgs")
set(nav_msgs_RUN_DEPENDS "geometry_msgs" "message_runtime" "std_msgs" "actionlib_msgs")
set(nav_msgs_TEST_DEPENDS )
set(nav_msgs_DOC_DEPENDS )
set(nav_msgs_URL_WEBSITE "http://wiki.ros.org/nav_msgs")
set(nav_msgs_URL_BUGTRACKER "")
set(nav_msgs_URL_REPOSITORY "")
set(nav_msgs_DEPRECATED "")