set(_CATKIN_CURRENT_PACKAGE "actionlib_msgs")
set(actionlib_msgs_VERSION "1.12.7")
set(actionlib_msgs_MAINTAINER "Tully Foote <tfoote@osrfoundation.org>")
set(actionlib_msgs_PACKAGE_FORMAT "1")
set(actionlib_msgs_BUILD_DEPENDS "message_generation" "std_msgs")
set(actionlib_msgs_BUILD_EXPORT_DEPENDS "message_generation" "message_runtime" "std_msgs")
set(actionlib_msgs_BUILDTOOL_DEPENDS "catkin")
set(actionlib_msgs_BUILDTOOL_DEPENDS_catkin_VERSION_GTE "0.5.78")
set(actionlib_msgs_BUILDTOOL_EXPORT_DEPENDS )
set(actionlib_msgs_EXEC_DEPENDS "message_generation" "message_runtime" "std_msgs")
set(actionlib_msgs_RUN_DEPENDS "message_generation" "message_runtime" "std_msgs")
set(actionlib_msgs_TEST_DEPENDS )
set(actionlib_msgs_DOC_DEPENDS )
set(actionlib_msgs_URL_WEBSITE "http://wiki.ros.org/actionlib_msgs")
set(actionlib_msgs_URL_BUGTRACKER "")
set(actionlib_msgs_URL_REPOSITORY "")
set(actionlib_msgs_DEPRECATED "")