# generated from genmsg/cmake/pkg-genmsg.context.in

messages_str = "/home/pi/gorobots/projects/geckoboti/catkin_ws_GeRot/src/nav_msgs/msg/GridCells.msg;/home/pi/gorobots/projects/geckoboti/catkin_ws_GeRot/src/nav_msgs/msg/MapMetaData.msg;/home/pi/gorobots/projects/geckoboti/catkin_ws_GeRot/src/nav_msgs/msg/OccupancyGrid.msg;/home/pi/gorobots/projects/geckoboti/catkin_ws_GeRot/src/nav_msgs/msg/Odometry.msg;/home/pi/gorobots/projects/geckoboti/catkin_ws_GeRot/src/nav_msgs/msg/Path.msg;/home/pi/gorobots/projects/geckoboti/catkin_ws_GeRot/devel_isolated/nav_msgs/share/nav_msgs/msg/GetMapAction.msg;/home/pi/gorobots/projects/geckoboti/catkin_ws_GeRot/devel_isolated/nav_msgs/share/nav_msgs/msg/GetMapActionGoal.msg;/home/pi/gorobots/projects/geckoboti/catkin_ws_GeRot/devel_isolated/nav_msgs/share/nav_msgs/msg/GetMapActionResult.msg;/home/pi/gorobots/projects/geckoboti/catkin_ws_GeRot/devel_isolated/nav_msgs/share/nav_msgs/msg/GetMapActionFeedback.msg;/home/pi/gorobots/projects/geckoboti/catkin_ws_GeRot/devel_isolated/nav_msgs/share/nav_msgs/msg/GetMapGoal.msg;/home/pi/gorobots/projects/geckoboti/catkin_ws_GeRot/devel_isolated/nav_msgs/share/nav_msgs/msg/GetMapResult.msg;/home/pi/gorobots/projects/geckoboti/catkin_ws_GeRot/devel_isolated/nav_msgs/share/nav_msgs/msg/GetMapFeedback.msg"
services_str = "/home/pi/gorobots/projects/geckoboti/catkin_ws_GeRot/src/nav_msgs/srv/GetMap.srv;/home/pi/gorobots/projects/geckoboti/catkin_ws_GeRot/src/nav_msgs/srv/GetPlan.srv;/home/pi/gorobots/projects/geckoboti/catkin_ws_GeRot/src/nav_msgs/srv/SetMap.srv"
pkg_name = "nav_msgs"
dependencies_str = "geometry_msgs;std_msgs;actionlib_msgs"
langs = "gencpp;geneus;genlisp;gennodejs;genpy"
dep_include_paths_str = "nav_msgs;/home/pi/gorobots/projects/geckoboti/catkin_ws_GeRot/src/nav_msgs/msg;nav_msgs;/home/pi/gorobots/projects/geckoboti/catkin_ws_GeRot/devel_isolated/nav_msgs/share/nav_msgs/msg;geometry_msgs;/home/pi/gorobots/projects/geckoboti/catkin_ws_GeRot/src/geometry_msgs/msg;std_msgs;/opt/ros/kinetic/share/std_msgs/cmake/../msg;actionlib_msgs;/home/pi/gorobots/projects/geckoboti/catkin_ws_GeRot/src/actionlib_msgs/msg"
PYTHON_EXECUTABLE = "/usr/bin/python2"
package_has_static_sources = '' == 'TRUE'
genmsg_check_deps_script = "/opt/ros/kinetic/share/genmsg/cmake/../../../lib/genmsg/genmsg_check_deps.py"
