set(_CATKIN_CURRENT_PACKAGE "diagnostic_msgs")
set(diagnostic_msgs_VERSION "1.12.7")
set(diagnostic_msgs_MAINTAINER "Tully Foote <tfoote@osrfoundation.org>")
set(diagnostic_msgs_PACKAGE_FORMAT "1")
set(diagnostic_msgs_BUILD_DEPENDS "message_generation" "std_msgs")
set(diagnostic_msgs_BUILD_EXPORT_DEPENDS "message_runtime" "std_msgs")
set(diagnostic_msgs_BUILDTOOL_DEPENDS "catkin")
set(diagnostic_msgs_BUILDTOOL_EXPORT_DEPENDS )
set(diagnostic_msgs_EXEC_DEPENDS "message_runtime" "std_msgs")
set(diagnostic_msgs_RUN_DEPENDS "message_runtime" "std_msgs")
set(diagnostic_msgs_TEST_DEPENDS )
set(diagnostic_msgs_DOC_DEPENDS )
set(diagnostic_msgs_URL_WEBSITE "http://wiki.ros.org/diagnostic_msgs")
set(diagnostic_msgs_URL_BUGTRACKER "")
set(diagnostic_msgs_URL_REPOSITORY "")
set(diagnostic_msgs_DEPRECATED "")