(cl:defpackage nav_msgs-srv
  (:use )
  (:export
   "GETMAP"
   "<GETMAP-REQUEST>"
   "GETMAP-REQUEST"
   "<GETMAP-RESPONSE>"
   "GETMAP-RESPONSE"
   "GETPLAN"
   "<GETPLAN-REQUEST>"
   "GETPLAN-REQUEST"
   "<GETPLAN-RESPONSE>"
   "GETPLAN-RESPONSE"
   "SETMAP"
   "<SETMAP-REQUEST>"
   "SETMAP-REQUEST"
   "<SETMAP-RESPONSE>"
   "SETMAP-RESPONSE"
  ))

