; Auto-generated. Do not edit!


(cl:in-package nav_msgs-msg)


;//! \htmlinclude GetMapFeedback.msg.html

(cl:defclass <GetMapFeedback> (roslisp-msg-protocol:ros-message)
  ()
)

(cl:defclass GetMapFeedback (<GetMapFeedback>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <GetMapFeedback>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'GetMapFeedback)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name nav_msgs-msg:<GetMapFeedback> is deprecated: use nav_msgs-msg:GetMapFeedback instead.")))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <GetMapFeedback>) ostream)
  "Serializes a message object of type '<GetMapFeedback>"
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <GetMapFeedback>) istream)
  "Deserializes a message object of type '<GetMapFeedback>"
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<GetMapFeedback>)))
  "Returns string type for a message object of type '<GetMapFeedback>"
  "nav_msgs/GetMapFeedback")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'GetMapFeedback)))
  "Returns string type for a message object of type 'GetMapFeedback"
  "nav_msgs/GetMapFeedback")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<GetMapFeedback>)))
  "Returns md5sum for a message object of type '<GetMapFeedback>"
  "d41d8cd98f00b204e9800998ecf8427e")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'GetMapFeedback)))
  "Returns md5sum for a message object of type 'GetMapFeedback"
  "d41d8cd98f00b204e9800998ecf8427e")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<GetMapFeedback>)))
  "Returns full string definition for message of type '<GetMapFeedback>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# no feedback~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'GetMapFeedback)))
  "Returns full string definition for message of type 'GetMapFeedback"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# no feedback~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <GetMapFeedback>))
  (cl:+ 0
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <GetMapFeedback>))
  "Converts a ROS message object to a list"
  (cl:list 'GetMapFeedback
))
