set(_CATKIN_CURRENT_PACKAGE "stereo_msgs")
set(stereo_msgs_VERSION "1.12.7")
set(stereo_msgs_MAINTAINER "Tully Foote <tfoote@osrfoundation.org>")
set(stereo_msgs_PACKAGE_FORMAT "1")
set(stereo_msgs_BUILD_DEPENDS "message_generation" "sensor_msgs" "std_msgs")
set(stereo_msgs_BUILD_EXPORT_DEPENDS "message_runtime" "sensor_msgs" "std_msgs")
set(stereo_msgs_BUILDTOOL_DEPENDS "catkin")
set(stereo_msgs_BUILDTOOL_EXPORT_DEPENDS )
set(stereo_msgs_EXEC_DEPENDS "message_runtime" "sensor_msgs" "std_msgs")
set(stereo_msgs_RUN_DEPENDS "message_runtime" "sensor_msgs" "std_msgs")
set(stereo_msgs_TEST_DEPENDS )
set(stereo_msgs_DOC_DEPENDS )
set(stereo_msgs_URL_WEBSITE "http://wiki.ros.org/stereo_msgs")
set(stereo_msgs_URL_BUGTRACKER "")
set(stereo_msgs_URL_REPOSITORY "")
set(stereo_msgs_DEPRECATED "")