; Auto-generated. Do not edit!


(cl:in-package nav_msgs-msg)


;//! \htmlinclude GetMapGoal.msg.html

(cl:defclass <GetMapGoal> (roslisp-msg-protocol:ros-message)
  ()
)

(cl:defclass GetMapGoal (<GetMapGoal>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <GetMapGoal>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'GetMapGoal)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name nav_msgs-msg:<GetMapGoal> is deprecated: use nav_msgs-msg:GetMapGoal instead.")))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <GetMapGoal>) ostream)
  "Serializes a message object of type '<GetMapGoal>"
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <GetMapGoal>) istream)
  "Deserializes a message object of type '<GetMapGoal>"
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<GetMapGoal>)))
  "Returns string type for a message object of type '<GetMapGoal>"
  "nav_msgs/GetMapGoal")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'GetMapGoal)))
  "Returns string type for a message object of type 'GetMapGoal"
  "nav_msgs/GetMapGoal")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<GetMapGoal>)))
  "Returns md5sum for a message object of type '<GetMapGoal>"
  "d41d8cd98f00b204e9800998ecf8427e")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'GetMapGoal)))
  "Returns md5sum for a message object of type 'GetMapGoal"
  "d41d8cd98f00b204e9800998ecf8427e")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<GetMapGoal>)))
  "Returns full string definition for message of type '<GetMapGoal>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Get the map as a nav_msgs/OccupancyGrid~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'GetMapGoal)))
  "Returns full string definition for message of type 'GetMapGoal"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Get the map as a nav_msgs/OccupancyGrid~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <GetMapGoal>))
  (cl:+ 0
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <GetMapGoal>))
  "Converts a ROS message object to a list"
  (cl:list 'GetMapGoal
))
