set(_CATKIN_CURRENT_PACKAGE "visualization_msgs")
set(visualization_msgs_VERSION "1.12.7")
set(visualization_msgs_MAINTAINER "Tully Foote <tfoote@osrfoundation.org>")
set(visualization_msgs_PACKAGE_FORMAT "1")
set(visualization_msgs_BUILD_DEPENDS "geometry_msgs" "message_generation" "std_msgs")
set(visualization_msgs_BUILD_EXPORT_DEPENDS "geometry_msgs" "message_runtime" "std_msgs")
set(visualization_msgs_BUILDTOOL_DEPENDS "catkin")
set(visualization_msgs_BUILDTOOL_EXPORT_DEPENDS )
set(visualization_msgs_EXEC_DEPENDS "geometry_msgs" "message_runtime" "std_msgs")
set(visualization_msgs_RUN_DEPENDS "geometry_msgs" "message_runtime" "std_msgs")
set(visualization_msgs_TEST_DEPENDS )
set(visualization_msgs_DOC_DEPENDS )
set(visualization_msgs_URL_WEBSITE "http://ros.org/wiki/visualization_msgs")
set(visualization_msgs_URL_BUGTRACKER "")
set(visualization_msgs_URL_REPOSITORY "")
set(visualization_msgs_DEPRECATED "")