set(_CATKIN_CURRENT_PACKAGE "sensor_msgs")
set(sensor_msgs_VERSION "1.12.7")
set(sensor_msgs_MAINTAINER "Tully Foote <tfoote@osrfoundation.org>")
set(sensor_msgs_PACKAGE_FORMAT "3")
set(sensor_msgs_BUILD_DEPENDS "geometry_msgs" "message_generation" "std_msgs")
set(sensor_msgs_BUILD_EXPORT_DEPENDS )
set(sensor_msgs_BUILDTOOL_DEPENDS "catkin" "python-setuptools" "python3-setuptools")
set(sensor_msgs_BUILDTOOL_EXPORT_DEPENDS )
set(sensor_msgs_EXEC_DEPENDS "geometry_msgs" "message_runtime" "std_msgs")
set(sensor_msgs_RUN_DEPENDS "geometry_msgs" "message_runtime" "std_msgs")
set(sensor_msgs_TEST_DEPENDS "rosbag" "rosunit")
set(sensor_msgs_DOC_DEPENDS )
set(sensor_msgs_URL_WEBSITE "http://ros.org/wiki/sensor_msgs")
set(sensor_msgs_URL_BUGTRACKER "")
set(sensor_msgs_URL_REPOSITORY "")
set(sensor_msgs_DEPRECATED "")