set(sensor_msgs_SETUP_PY_VERSION "1.12.7")
set(sensor_msgs_SETUP_PY_SCRIPTS "")
set(sensor_msgs_SETUP_PY_PACKAGES "sensor_msgs")
set(sensor_msgs_SETUP_PY_PACKAGE_DIRS "src/sensor_msgs")
set(sensor_msgs_SETUP_PY_MODULES "")
set(sensor_msgs_SETUP_PY_MODULE_DIRS "")