set(_CATKIN_CURRENT_PACKAGE "shape_msgs")
set(shape_msgs_VERSION "1.12.7")
set(shape_msgs_MAINTAINER "Ioan Sucan <isucan@willowgarage.com>")
set(shape_msgs_PACKAGE_FORMAT "1")
set(shape_msgs_BUILD_DEPENDS "geometry_msgs" "message_generation" "std_msgs")
set(shape_msgs_BUILD_EXPORT_DEPENDS "geometry_msgs" "message_runtime" "std_msgs")
set(shape_msgs_BUILDTOOL_DEPENDS "catkin")
set(shape_msgs_BUILDTOOL_EXPORT_DEPENDS )
set(shape_msgs_EXEC_DEPENDS "geometry_msgs" "message_runtime" "std_msgs")
set(shape_msgs_RUN_DEPENDS "geometry_msgs" "message_runtime" "std_msgs")
set(shape_msgs_TEST_DEPENDS )
set(shape_msgs_DOC_DEPENDS )
set(shape_msgs_URL_WEBSITE "http://wiki.ros.org/shape_msgs")
set(shape_msgs_URL_BUGTRACKER "")
set(shape_msgs_URL_REPOSITORY "")
set(shape_msgs_DEPRECATED "")