(cl:in-package sensor_msgs-msg)
(cl:export '(HEADER-VAL
          HEADER
          VOLTAGE-VAL
          VOLTAGE
          CURRENT-VAL
          CURRENT
          CHARGE-VAL
          CHARGE
          CAPACITY-VAL
          CAPACITY
          DESIGN_CAPACITY-VAL
          DESIGN_CAPACITY
          PERCENTAGE-VAL
          PERCENTAGE
          POWER_SUPPLY_STATUS-VAL
          POWER_SUPPLY_STATUS
          POWER_SUPPLY_HEALTH-VAL
          POWER_SUPPLY_HEALTH
          POWER_SUPPLY_TECHNOLOGY-VAL
          POWER_SUPPLY_TECHNOLOGY
          PRESENT-VAL
          PRESENT
          CELL_VOLTAGE-VAL
          CELL_VOLTAGE
          LOCATION-VAL
          LOCATION
          SERIAL_NUMBER-VAL
          SERIAL_NUMBER
))