set(_CATKIN_CURRENT_PACKAGE "geometry_msgs")
set(geometry_msgs_VERSION "1.12.7")
set(geometry_msgs_MAINTAINER "Tully Foote <tfoote@osrfoundation.org>")
set(geometry_msgs_PACKAGE_FORMAT "1")
set(geometry_msgs_BUILD_DEPENDS "message_generation" "std_msgs")
set(geometry_msgs_BUILD_EXPORT_DEPENDS "message_runtime" "std_msgs")
set(geometry_msgs_BUILDTOOL_DEPENDS "catkin")
set(geometry_msgs_BUILDTOOL_EXPORT_DEPENDS )
set(geometry_msgs_EXEC_DEPENDS "message_runtime" "std_msgs")
set(geometry_msgs_RUN_DEPENDS "message_runtime" "std_msgs")
set(geometry_msgs_TEST_DEPENDS )
set(geometry_msgs_DOC_DEPENDS )
set(geometry_msgs_URL_WEBSITE "http://wiki.ros.org/geometry_msgs")
set(geometry_msgs_URL_BUGTRACKER "")
set(geometry_msgs_URL_REPOSITORY "")
set(geometry_msgs_DEPRECATED "")